### ISSUE TITLE
how to calculate elevation_thresholds and flatness_thresholds

### ISSUE THREAD

**Issue by ralphoon** [LimHyungTae/patchwork#1]
Hello,
  Thanks for your open source!
  I  would like to ask what function  elevation_thresholds and flatness_thresholds are calculated according to

**Comment by LimHyungTae** [comment]
Oops, sorry for the late response due to the ICRA'22..haha.

I'll upload it ASAP

**Comment by LimHyungTae** [comment]
Hello, ralphoon
I added additional explanations about elevation_thresholds.
Since the original parameters are for KITTI, but you can change them depending on your own environment.
[elevation_thresholds]
* If your env is strictly flat, then set the elevation_thresholds to be similar to the sensor height.
[flatness_thresholds]
* The surface variable is usually set to 0.02 in many papers to estimate whether the target unit cloud is flat or not.
* But I recommend setting flatness_thresholds in a more strict way

The best way is to check the printed command line in your command window and then set proper parameters.
If the `verbose` is true, you can show the below commands:

**Comment by LimHyungTae** [comment]
![image](https://user-images.githubusercontent.com/35317311/133909565-ecfedfc0-7a84-48e3-800d-c8f141f0be4a.png)
Like this

**Comment by ralphoon** [comment]
Thank you very much for your reply, it is very useful to me！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LimHyungTae/patchwork"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月19日(星期天) 凌晨5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LimHyungTae/patchwork] how to calculate elevation_thresholds and flatness_thresholds (#1)





 

 Like this
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
