### ISSUE TITLE
Why is elevation_threshold different for each zone?

### ISSUE THREAD

**Issue by natashasoon** [LimHyungTae/patchwork#13]
Hi,

I read through your paper explaining the patchwork algorithm, but need a little more clarification on why different elevation thresholds are needed for each zone. 

If I am understanding the parameter correctly, the elevation thresholds represent the adaptive midpoint function κ(r). Would I be correct to say that this parameter is simply the maximum height that the ground plane can be? In this case, why would the maximum ground height change depending on the distance of each zone?

Thanks!

**Comment by LimHyungTae** [comment]
Hello there, sorry for the late reply due to my paper works.

Because as the distance goes farther, we cannot sure that the z values of the ground have lower height. The elevation threshold is based on the fact that the z values of the ground are likely to be similar to the -h, where h is the sensor height. But there are some exceptional cases, such as steep slopes. It might have some higher z values. Therefore, it should become larger as the ring index is getting bigger.
